### Numpy :

Numpy est l'abréviation de Numerical python , c'est une bibliothèque python open source, elle contient :
- des structures de données des tableaux multidimensionnels (ndarray).
- et riche par des fonctions de manipulations des tableaux.

l'API numpy est utilisée dans pandas, SciPy, Matplotlib, scikit-learn, scikit-image et la plupart des autres packages de science des données et de Python scientifique.

### installation de numpy¶

- pip install numpy
- conda install numpy 
- ou par la distribution Anaconda.

In [1]:
import numpy as np

In [2]:
# Tableau 1D
a = np.array([1,3,5])
print(a)

[1 3 5]


In [3]:
# Tableau 2D (matrice)
b = np.array([
    [9.0,3.0,5.0],
    [1.0,2.0,9.0]
])
print(b)
c = np.array([0])
c

[[9. 3. 5.]
 [1. 2. 9.]]


array([0])

In [4]:
# Get dimension(nbre de lignes, nbre de colonnes)
c.ndim

1

In [5]:
# Get shape (nombre d'éléments)
b.shape

(2, 3)

In [6]:
# Get type
b.dtype

dtype('float64')

In [7]:
# transposé d'une matrice :
b.T

array([[9., 1.],
       [3., 2.],
       [5., 9.]])

In [8]:
# Get size(byte = octet)
a.itemsize

8

In [9]:
a.size

3

In [10]:
# Get total size
a.size * a.itemsize # = a.nbytes

24

# Accéder/changer des éléments spécifiques, lignes, colonnes etc

In [11]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [lignes, colonnes] les indices à partir de 0
c[1,6]

14

In [13]:
# Get a specific ligne
c[0]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific colonne
c[:,0]

array([1, 8])

In [15]:
# Getting a little more fancy [startindex:endindex:stepindex]
c[0,1:6:4]

array([2, 6])

In [16]:
# Replace 13 par 20 du 2ième ligne et 6ième colonne
c[1,5] = 20
print(c)

c[:,2] = [70,80]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 70  4  5  6  7]
 [ 8  9 80 11 12 20 14]]


In [17]:
# Tableau 3D (matrice)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [19]:
a = np.ones(3)
a

array([1., 1., 1.])

In [20]:
z = np.empty(5)
z

array([2.58205058e-057, 1.95042335e+160, 6.87069596e-038, 1.60437383e-051,
       9.34243567e+164])

In [21]:
z.shape

(5,)

In [22]:

a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [23]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [24]:
a_list = [1,2,3,4,6]
a= np.array(a_list)
a

array([1, 2, 3, 4, 6])

In [25]:
np.random.seed(0) # obtenir les memes nombres aléatoires
z1 = np.random.randint(25, size=8) # générer des nombres aléatoires entre 0 et 25, tableau de taille 8
z1

array([12, 15, 21,  0,  3,  3,  7,  9])

In [26]:
z1[0]

12

In [27]:
z1[0:5]

array([12, 15, 21,  0,  3])

In [28]:
z1[-1] # dernier élément

9